export enum UserRole { INVENTOR = 'INVENTOR', UNIVERSITY = 'UNIVERSITY', STARTUP = 'STARTUP', ENTERPRISE = 'ENTERPRISE', BROKER = 'BROKER', ADMIN = 'ADMIN' }
export enum UserStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', SUSPENDED = 'SUSPENDED', PENDING_VERIFICATION = 'PENDING_VERIFICATION' }
export enum PatentStatus { PROVISIONAL = 'PROVISIONAL', FILED = 'FILED', PUBLISHED = 'PUBLISHED', GRANTED = 'GRANTED', ABANDONED = 'ABANDONED', EXPIRED = 'EXPIRED', LICENSED = 'LICENSED' }
export enum PatentType { UTILITY = 'UTILITY', DESIGN = 'DESIGN', PLANT = 'PLANT', PCT = 'PCT', CONTINUATION = 'CONTINUATION', DIVISIONAL = 'DIVISIONAL' }
export enum DealStatus { INQUIRY = 'INQUIRY', NDA_SENT = 'NDA_SENT', NDA_SIGNED = 'NDA_SIGNED', TERM_SHEET = 'TERM_SHEET', DUE_DILIGENCE = 'DUE_DILIGENCE', NEGOTIATING = 'NEGOTIATING', AGREEMENT_DRAFT = 'AGREEMENT_DRAFT', SIGNED = 'SIGNED', ACTIVE = 'ACTIVE', COMPLETED = 'COMPLETED', TERMINATED = 'TERMINATED' }
export enum DealType { EXCLUSIVE_LICENSE = 'EXCLUSIVE_LICENSE', NON_EXCLUSIVE_LICENSE = 'NON_EXCLUSIVE_LICENSE', CROSS_LICENSE = 'CROSS_LICENSE', ASSIGNMENT = 'ASSIGNMENT', JOINT_VENTURE = 'JOINT_VENTURE', SPONSORED_RESEARCH = 'SPONSORED_RESEARCH', OPTION_AGREEMENT = 'OPTION_AGREEMENT' }
export enum MessageType { TEXT = 'TEXT', FILE = 'FILE', DEAL_PROPOSAL = 'DEAL_PROPOSAL', NDA_REQUEST = 'NDA_REQUEST', COUNTER_OFFER = 'COUNTER_OFFER', SYSTEM = 'SYSTEM', MILESTONE = 'MILESTONE' }
export enum RoyaltyStatus { PENDING = 'PENDING', PAID = 'PAID', OVERDUE = 'OVERDUE', DISPUTED = 'DISPUTED', WAIVED = 'WAIVED' }
export enum ReportType { AI_PORTFOLIO = 'AI_PORTFOLIO', VALUATION = 'VALUATION', COMMERCIALIZATION = 'COMMERCIALIZATION', BUYER_MATCH = 'BUYER_MATCH', DEAL_SUMMARY = 'DEAL_SUMMARY', ROYALTY_COLLECTION = 'ROYALTY_COLLECTION', PLATFORM_ANALYTICS = 'PLATFORM_ANALYTICS' }
export enum ReportFormat { PDF = 'PDF', EXCEL = 'EXCEL', CSV = 'CSV', JSON = 'JSON' }
export enum NotificationType { DEAL = 'DEAL', PATENT = 'PATENT', AI = 'AI', ROYALTY = 'ROYALTY', MESSAGE = 'MESSAGE', SYSTEM = 'SYSTEM' }
export enum TechDomain { AI_ML = 'AI_ML', BIOTECH = 'BIOTECH', CLEAN_TECH = 'CLEAN_TECH', SEMICONDUCTOR = 'SEMICONDUCTOR', HEALTHCARE = 'HEALTHCARE', ENERGY = 'ENERGY', AGRICULTURE = 'AGRICULTURE', MANUFACTURING = 'MANUFACTURING', MATERIALS = 'MATERIALS', DEFENSE = 'DEFENSE', IT_SOFTWARE = 'IT_SOFTWARE', AUTOMOTIVE = 'AUTOMOTIVE', PHARMA = 'PHARMA', NANOTECHNOLOGY = 'NANOTECHNOLOGY', OTHER = 'OTHER' }
export namespace Prisma {
  export type PatentScalarFieldEnum = any;
  export type SortOrder = 'asc' | 'desc';
  export type PatentWhereInput = any;
}
